title: "TAB"
theme: jekyll-theme-cayman

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "angkoonhwee.github.io/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
